Create README.md
open-switch/opx-snmp pull request #2
Opened 2018-06-08 17:33 UTC by nchervela

2018-06-11 19:48 UTC, jeff-yin commented
Document needs proper markdown formatting throughout

2018-06-11 19:49 UTC, jeffyin-dell requested changes
Needs markdown throughout document

2018-06-25 19:03 UTC, jeff-yin commented
@nchervela any update?

2018-06-25 21:59 UTC, nchervela commented
Per email below, Amy added the markdowns.  thanks!
=============================
I’ve added the file in markdown 

Amy Buck
Technical Content Developer 3 | 2018 Dell Champion

2018-06-28 18:13 UTC, nchervela commented
@jyin - Done.  thanks.

2018-06-28 18:20 UTC, jeffyin-dell requested changes

2018-06-28 18:20 UTC, jeff-yin commented on README.md
> +
nitpick: Why so much whitespace?

2018-06-28 18:20 UTC, jeff-yin commented on README.md
> +compiled MIPS:                 /usr/lib/python2.7/dist-packages/opx-snmp
First character of each line should be capitalized

2018-06-28 18:20 UTC, jeff-yin commented on README.md
> +interface table
This should be a bulleted list, and the first character should be capitalized

2018-06-28 18:20 UTC, jeff-yin commented on README.md
> +This document describes SNMP agent implementation for
nitpick: don't think you need these manual line breaks

2018-06-28 18:46 UTC, nchervela commented
@jyin addressed review comments.

2018-06-28 18:46 UTC, jeff-yin commented
@amybuck please review

2018-06-28 18:47 UTC, jeffyin-dell submitted a review, later dismissed

2018-06-29 00:15 UTC, jeffyin-dell requested changes
I wrote in an e-mail that you're still missing a couple of the changes suggested by Amy. ALSO, the commit signoff is missing! Did you commit using `git commit -s` before opening the pull-request?
https://github.com/open-switch/opx-docs/wiki/Contributor-guide

2018-06-29 18:26 UTC, jeffyin-dell requested changes
Still no sign-off :(

2018-06-29 18:27 UTC, jeffyin-dell requested changes

2018-06-29 18:27 UTC, jeffyin-dell commented on README.md
> +This file describes the SNMP agent implementation for OpenSwitch OPX.  The engine used is PySNMP, which is a lightweight Python-based extensible agent with rich functionality.  The agent implementati
Suggest changing "This file describes the SNMP agent implementation for OpenSwitch OPX." to "This is the SNMP agent for OpenSwitch OPX."

2018-07-06 22:29 UTC, jeff-yin commented
@nchervela please advise when you have a pull-request created with a signed commit. We will close this in favor of that one.

2018-07-10 17:57 UTC, jeff-yin commented
@nchervela update?

2018-07-10 22:51 UTC, closed without merging