refactor: code to install files
open-switch/opx-snmp pull request #7
Opened 2018-08-17 23:44 UTC by Tejaswi-Goel

* Update: remove postinst script
* Update: change install path for opx-snmp
* Update: Replace the default __SNMPv2-MIB.py file in pysnmp package with the customized __SNMPv2-MIB.py

Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

2018-08-19 13:57 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now c5431110a211f2189d206db0fdbaec9b582ee578

2018-08-20 17:32 UTC, jeffyin-dell requested changes

2018-08-20 17:32 UTC, jeff-yin commented on debian/changelog
> +  * Update: Remove posinst script
typo here: "posinst" is missing a 't'

2018-08-20 17:35 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now 35bffeb4fc452025a2ce09edbb835832014475f7

2018-08-20 19:10 UTC, jeffyin-dell approved these changes

2018-08-20 20:57 UTC, hpersh approved these changes

2018-08-20 20:59 UTC, merged